version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres_17
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: auth
      POSTGRES_PASSWORD: auth-password
    ports:
      - "5432:5432"

  auth-java:
    build: .
    container_name: auth-java
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/auth
      DATABASE_USERNAME: auth
      DATABASE_PASSWORD: auth-password
